version: '3.7'
services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    tty: true
